"""initial schema

Revision ID: 625600a5b6b7
Revises: 
Create Date: 2026-06-18 17:39:09.380142
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '625600a5b6b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('superadmin', 'admin', 'moderator', 'user', name='role'), nullable=False),
    sa.Column('real_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plex_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plex_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plex_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notify_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telegram_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_user_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_user_plex_account_id'), ['plex_account_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_app_user_plex_email'), ['plex_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_user_plex_username'), ['plex_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_user_telegram_id'), ['telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_user_username'), ['username'], unique=True)

    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('is_unlimited', sa.Boolean(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_slug'), ['slug'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)

    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('real_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intended_role', sa.Enum('superadmin', 'admin', 'moderator', 'user', name='role'), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('trial_days', sa.Integer(), nullable=True),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', name='invitestatus'), nullable=False),
    sa.Column('plex_invite_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invite_token'), ['token'], unique=True)

    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('expiry_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'expired', 'cancelled', name='subscriptionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_user_id'), ['user_id'], unique=False)

    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('expiry_7d', 'expiry_3d', 'expiry_1d', 'manager_collect', 'broadcast', name='notificationtype'), nullable=False),
    sa.Column('channel', sa.Enum('email', 'telegram', name='notificationchannel'), nullable=False),
    sa.Column('dedup_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_log_dedup_key'), ['dedup_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_notification_log_user_id'), ['user_id'], unique=False)

    op.create_table('renewal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', name='renewalstatus'), nullable=False),
    sa.Column('causale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('collected_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collected_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('renewal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_renewal_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_renewal_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_renewal_subscription_id'), ['subscription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('renewal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_renewal_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_renewal_status'))
        batch_op.drop_index(batch_op.f('ix_renewal_paid_at'))

    op.drop_table('renewal')
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_log_dedup_key'))

    op.drop_table('notification_log')
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_status'))

    op.drop_table('subscription')
    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_token'))
        batch_op.drop_index(batch_op.f('ix_invite_status'))
        batch_op.drop_index(batch_op.f('ix_invite_email'))

    op.drop_table('invite')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_slug'))

    op.drop_table('plan')
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_user_username'))
        batch_op.drop_index(batch_op.f('ix_app_user_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_app_user_role'))
        batch_op.drop_index(batch_op.f('ix_app_user_plex_username'))
        batch_op.drop_index(batch_op.f('ix_app_user_plex_email'))
        batch_op.drop_index(batch_op.f('ix_app_user_plex_account_id'))
        batch_op.drop_index(batch_op.f('ix_app_user_is_active'))

    op.drop_table('app_user')
    # ### end Alembic commands ###
